# Generated by Django 5.1.2 on 2024-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/avatars/default.png', upload_to='avatars'),
        ),
    ]
